// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by scripts/generate_version.ps1 (or fallback)

const String appVersion = '1.2.1+77';
const String appBuildTime = '2026-09-12T04:40:12.058427Z';
