param(
  [string]$SupabaseUrl = $env:SUPABASE_URL,
  [string]$SupabaseAnonKey = $env:SUPABASE_ANON_KEY,
  [string]$ProjectRef = $env:SUPABASE_PROJECT_REF,
  [string]$OutputPath,
  [switch]$Force,
  [switch]$DryRun
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path $PSScriptRoot -Parent
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $repoRoot ".env"
}

function Read-RequiredValue {
  param(
    [string]$Name,
    [string]$Value,
    [string]$Prompt
  )

  if (-not [string]::IsNullOrWhiteSpace($Value)) {
    return $Value.Trim()
  }

  $enteredValue = Read-Host $Prompt
  if ([string]::IsNullOrWhiteSpace($enteredValue)) {
    throw "$Name is required."
  }

  return $enteredValue.Trim()
}

function Test-PlaceholderValue {
  param([string]$Value)

  return [string]::IsNullOrWhiteSpace($Value) -or
    $Value -like "YOUR_*" -or
    $Value -like "*YOUR_PROJECT*"
}

function Assert-RealValue {
  param(
    [string]$Name,
    [string]$Value
  )

  if (Test-PlaceholderValue -Value $Value) {
    throw "$Name must be a real production value, not a placeholder."
  }

  if ($Value.Contains("`r") -or $Value.Contains("`n")) {
    throw "$Name cannot contain line breaks."
  }
}

$SupabaseUrl = Read-RequiredValue `
  -Name "SUPABASE_URL" `
  -Value $SupabaseUrl `
  -Prompt "Supabase project URL, for example https://your-project.supabase.co"

$SupabaseAnonKey = Read-RequiredValue `
  -Name "SUPABASE_ANON_KEY" `
  -Value $SupabaseAnonKey `
  -Prompt "Supabase anon key"

$ProjectRef = Read-RequiredValue `
  -Name "SUPABASE_PROJECT_REF" `
  -Value $ProjectRef `
  -Prompt "Supabase project ref"

Assert-RealValue -Name "SUPABASE_URL" -Value $SupabaseUrl
Assert-RealValue -Name "SUPABASE_ANON_KEY" -Value $SupabaseAnonKey
Assert-RealValue -Name "SUPABASE_PROJECT_REF" -Value $ProjectRef

$parsedUrl = $null
if (-not [System.Uri]::TryCreate($SupabaseUrl, [System.UriKind]::Absolute, [ref]$parsedUrl)) {
  throw "SUPABASE_URL must be a valid absolute URL."
}

if ($parsedUrl.Scheme -ne "https") {
  throw "SUPABASE_URL must use https."
}

if ($ProjectRef -notmatch "^[a-z0-9-]+$") {
  throw "SUPABASE_PROJECT_REF should contain only lowercase letters, numbers, and hyphens."
}

if ((Test-Path -LiteralPath $OutputPath -PathType Leaf) -and -not $Force) {
  throw "$OutputPath already exists. Use -Force to replace it."
}

$content = @"
# Ivra Flutter/Supabase environment
#
# Generated by scripts/setup_supabase_env.ps1.
# This file is ignored by git. Do not commit real Supabase values.

SUPABASE_URL=$SupabaseUrl
SUPABASE_ANON_KEY=$SupabaseAnonKey
SUPABASE_PROJECT_REF=$ProjectRef

# Optional helpers for scripts/render_supabase_sql.ps1
IVRA_APP_ADMIN_ID=00000000-0000-0000-0000-000000000001
IVRA_APP_MANAGER_ID=00000000-0000-0000-0000-000000000002
IVRA_HOTEL_MANAGER_ID=00000000-0000-0000-0000-000000000003
IVRA_HOTEL_STAFF_ID=00000000-0000-0000-0000-000000000004
IVRA_RLS_HOTEL_A_ID=10000000-0000-4000-8000-000000000001
IVRA_RLS_HOTEL_B_ID=10000000-0000-4000-8000-000000000002
IVRA_ADMIN_EMAIL=admin@your-company.com
IVRA_APP_MANAGER_EMAIL=manager@your-company.com
IVRA_HOTEL_MANAGER_EMAIL=hotel-manager@hotel.com
IVRA_HOTEL_STAFF_EMAIL=staff@hotel.com
IVRA_ADMIN_FULL_NAME=Ivra Admin
"@

Write-Host "Ivra Supabase environment setup"
Write-Host "Target: $OutputPath"
Write-Host "Project ref: $ProjectRef"
Write-Host "URL host: $($parsedUrl.Host)"

if ($DryRun) {
  Write-Host "Dry run complete. No file was written."
  exit 0
}

$outputDirectory = Split-Path $OutputPath -Parent
if (-not [string]::IsNullOrWhiteSpace($outputDirectory)) {
  New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $content -Encoding UTF8

Write-Host ""
Write-Host "Created $OutputPath."
Write-Host "Next steps:"
Write-Host "1. Run .\scripts\deploy_supabase.ps1 -DryRun."
Write-Host "2. Run .\scripts\deploy_supabase.ps1 when the Supabase CLI is ready."
Write-Host "3. Render and run the first-admin, seed, and RLS verification SQL files."
